### ISSUE TITLE
Panic when socket is closed

### ISSUE THREAD

**Issue by anetor46** [binance/binance-spot-connector-rust#19]
Hello,

When the socket is getting closed for any reason, the send method panic due to the call of the `unwrap` method:
```
thread 'tokio-runtime-worker' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/binance_spot_connector_rust-1.1.0/src/tokio_tun>
called `Result::unwrap()` on an `Err` value: AlreadyClosed
```

https://github.com/binance/binance-spot-connector-rust/blob/e7293ef2aae12f7442979607bd869598b86a9ced/src/tokio_tungstenite.rs#L69

Would it be possible to change this behaviour to avoid a panic, it might be complex to catch and make it difficult to build a robust service. Ideally while receiving message from the websocket it should return an Error in the result of the `next()` method of the connection object when this happen, allowing to rebuild the connection property and not crash the service.

**Comment by alplabin** [comment]
Hey,
When you say `closed for any reason`, do you mean that the WebSocket stream returned an error that closed the connection? Do you have a way to reproduce this error?
