### ISSUE TITLE
examples/market /ticker_twenty_four_hr  need update

### ISSUE THREAD

**Issue by hgzhehe** [binance/binance-spot-connector-rust#21]
let request = market::ticker_twenty_four_hr()
        .symbol("BNBUSDT")
        .symbols(vec!["BTCUSDT", "BNBBTC"]);

code: -1128, message: "Combination of optional parameters invalid. Recommendation: 'symbol' and 'symbols' cannot both be sent."

**Comment by alplabin** [comment]
Thanks for pointing out this issue. It has been updated in the latest release: [v1.3.0](https://github.com/binance/binance-spot-connector-rust/releases/tag/v1.3.0)
