### ISSUE TITLE
does it handle the 24hr disconnect?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [binance/binance-spot-connector-rust#26]
![image](https://github.com/user-attachments/assets/b2f48e9d-35d6-4059-8054-c8ffc37c2afa)
The API docs say that every websocket connection is closed after roughly 24 hours. If so, is there any logic in this client for an automatic reconnection procedure? Or is one expected to implement this oneself? thx

**Comment by alplabin** [comment]
This client doesn't have currently an automatic reconnection procedure. You will need to implement it on your end.
